### ISSUE TITLE
problems with defschema

### ISSUE THREAD

**Issue by Cottin** [Prismatic/om-tools#60]
When following your example and adding

```
(ns ideas.component.idea
  (:require
    [om.core :as om]
    [om-tools.core :refer-macros [defcomponentk]]
    [schema.core :refer-macros [defschema]]))

(defschema ProgressBar      <----- line 27
  {:value js/Number
   (s/optional-key :min) js/Number
   (s/optional-key :max) js/Number})
```

I get the following compilation error:

```
Caused by: clojure.lang.ExceptionInfo: clojure.lang.Var cannot be cast to
clojure.lang.IObj at line 27 src/cljs/ideas/components/idea.cljs
{:tag :cljs/analysis-error, :file "src/cljs/ideas/components/idea.cljs", :line 27, :column 1}
```

I thought maybe I needed to explicitly add a dep to schema:

```
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-2371" :scope "provided"]
                ...
                 [prismatic/schema "0.3.3"]
                 [prismatic/om-tools "0.3.6"]
```

But then after a `lein cljsbuild clean` and a `lein cljsbuild once` I get another compilation error:

```
clojure.lang.ExceptionInfo: java.lang.ExceptionInInitializerError, compiling:(schema/macros.clj:1:1) at line 1  {:tag :cljs/analysis-error, :file nil, :line 1, :column 1}
```

Am I missing something?

**Comment by kernelp4nic** [comment]
We had the same problem, the offending was an old version of [schema](https://github.com/Prismatic/schema), updating to the lastest version resolved the issue.

**Comment by loganlinn** [comment]
@kernelp4nic Thanks for following up. This does sound like an issue from conflicting or old schema versions. Going to close for now, but anyone should feel free to re-open if problem still exists.
