### ISSUE TITLE
Update to work with recent Om

### ISSUE THREAD

**Issue by atroche** [Prismatic/om-tools#69]
Hey guys,

Any plans to upgrade om-tools to work with the latest Om? I'm having all sorts of problems with externs, and it seems like recent versions simplify the way they work.

Cheers!

**Comment by loganlinn** [comment]
Are you seeing any particular issue with om-tools? I am not aware of any extern configuration that we need to change for downstream projects.

**Comment by atroche** [comment]
Hey @loganlinn, sorry for the false alarm — it was actually to do with the new version of ClojureScript. Thanks for all your efforts on `om-tools`! I'm so glad it exists =)
