### ISSUE TITLE
Single om/build inside a single dom/div does not render properly

### ISSUE THREAD

**Issue by cobalamin** [Prismatic/om-tools#70]
I'm writing a wrapper component and trying to just use a passed in view with `om/build` inside a wrapper `dom/div`. I noticed that using om-tools' dom helpers, the wrapper component doesn't seem to render at all. I set up a small test case:

```cljs
(defcomponent inner-view [data owner]
  (render [_]
    (dom/span "I'm working!")))

(defcomponent wrapper-view [data owner]
  (render [_]
    (dom/div
     (om/build inner-view nil))))
```

In the Chrome devtools, I'm actually seeing the wrapper div, but it looks odd and has no content:

```html
<div type="function (props) {
      // This constructor is overridden by mocks. The argument is used
      // by mocks to assert on what gets mounted. This will later be used
      // by the stand-alone class implementation.
    }" data-reactid=".0.0"></div>
```

I am able to work around the problem doing any of the following:

- use `om.dom/div nil ...` instead of `dom/div ...` (but then I could just use Om alone, right? ;)
- use `om/build-all inner-view [nil]` - this seems especially odd
- put any kind of content before `(om/build inner-view nil)`, e.g.:

```cljs
(dom/div ""
     (om/build inner-view nil))
```

It seems to me that the first argument, a view created with om/build, is interpreted incorrectly as an options map, or something of the like, leading to no content and that odd `type="..."` output.

I can't recall having this problem before using Om 0.8.8, but I don't remember if I ever had a single dom wrapper around a single om/build call.

I'm using Om 0.8.8 and om-tools 0.3.10.

**Comment by loganlinn** [comment]
Hey, thanks for the report. I am having trouble reproducing this. I attempted to repro by modifying the project under `examples/sliders` using [these changes](https://gist.github.com/loganlinn/38bf12d3810c19300f2f). This rendered "I'm working". Can you confirm you are still seeing this issue? If so, please provide ClojureScript version

**Comment by loganlinn** [comment]
Going to close. Feel free to re-open if you can still reproduce
