### ISSUE TITLE
came-case breaks in Safari 9 (11601.1.50) under El Capitan

### ISSUE THREAD

**Issue by terhechte** [Prismatic/om-tools#82]
Hey,

I just ran into an issue on El Capitan. I've also filed an Apple Rdar bug for this, but I doubt that they will look into this in time.

I have a ClojureScript app that runs within WebKit embedded in a Mac App. In there, I'm using om-tools. On El Capitan, the 'camel-case' fn in dom.cljx throws an exception for the input 'camelCase'.

In detail, this exception is thrown:
`Invalid match arg: /-(\w)/`

**Comment by dpetrovics** [comment]
Any update on this? We're running into this issue on a production app

**Comment by loganlinn** [comment]
I have not had a chance to dig into this issue yet. PR is welcome

**Comment by dpetrovics** [comment]
OK I think this was actually a cljs issue that was fixed with this commit: https://github.com/clojure/clojurescript/commit/d717b4edea074fcfd3e718a6134238ba26f76f82  After upgrading our (quite old) version of cljs the error went away.

**Comment by loganlinn** [comment]
@dpetrovics Thanks for reporting back. I had figured this was the case (a cljs compiler bug), as there shouldn't be anything irregular about the regex in the error.
