### ISSUE TITLE
Any plans to upgrade this to 1.7? 

### ISSUE THREAD

**Issue by acron0** [Prismatic/om-tools#83]
I ask because you're still using an old version of `plumbing` and when combined with a 1.7 project we get these warnings:

    WARNING: update already refers to: #'clojure.core/update in namespace: plumbing.core, being replaced by: #'plumbing.core/update

I know these are fixed in the latest `plumbing` :)

**Comment by loganlinn** [comment]
I've pushed a new version of om-tools with latest plumbing and schema: `[prismatic/om-tools "0.4.0"]`

Let me know if you have any issues!
